service: iam
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-plugin-ifelse

custom:
  isOffline: ${env:IS_OFFLINE, "false"}
  serverlessIfElse:
    - If: '"${self:custom.isOffline}" != "true"'
      Exclude:
        - functions.endpoint.handler
        - provider.environment.CODESPACE_NAME
        - provider.environment.DJANGO_DEBUG
      ElseExclude:
        - functions.endpoint.image

provider:
  name: aws
  region: eu-central-1

  environment:
    CODESPACE_NAME: ${env:CODESPACE_NAME, ""}
    DJANGO_DEBUG: 'on'
    POSTGRES_DB: app_db
    POSTGRES_USER: app_user
    POSTGRES_PASSWORD: changeme
    POSTGRES_PORT: 5432
    ENDPOINT_URL_IAM: ${env:ENDPOINT_URL_IAM, ""}
    DUCKDB_DATA_PATH: '/var/duckdb'

  ecr:
    images:
      appimage:
        path: ./

functions:
  endpoint:
    image:
      name: appimage
      command:
        - dist/app.handler
    handler: dist/app.handler
    events:
      - httpApi:
          path: '*'
          method: '*'

# SPDX-License-Identifier: (EUPL-1.2)
# Copyright © 2019-2022 snek.at
